version: '3.1'

services:
  mysql:
    image: mysql:8.0-oracle
    container_name: mysql-8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - canalsharp
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d/

    
  canal-server:
    image: canal/canal-server:v1.1.5
    container_name: canal-server
    ports:
      - "11111:11111"
    networks:
      - canalsharp
    volumes:
      - ./canal/example/:/home/admin/canal-server/conf/example/
      - ./canal/logs/:/home/admin/canal-server/logs/
    depends_on:
      - mysql

networks:
  canalsharp:
    driver: bridge